### PR TITLE
adds joplin as gold tier application

### PR DESCRIPTION
**Pull request by ghost**
[joplin](https://joplinapp.org/) note taking application verified to be working as implemented using latest stable build on pixel4/4a

### CODE REVIEW

**Comment by ghost** [comment]
[infinity](https://f-droid.org/en/packages/ml.docilealligator.infinityforreddit/) reddit reader has been fully tested on latest upstream stable build on pixel4/4a

**Comment by Peter-Easton** [comment]
Aw shoot. I accidentally rebased the wrong branch and ended up nuking the commit. I'm sorry about that. Could you send it back in again, please? My mistake.

**Comment by Peter-Easton** [comment]
Aw shoot. I made a mistake when rebasing, and I lost the commit! I'm sorry about that. Could you send it back in again, please? It's my mistake. I'll try to figure out what wrong and try to merge it back again in the meantime.

**Comment by Peter-Easton** [comment]
@xrk37 could you send me an E-mail at peter@jollyrogers.ca, please?

**Pull request merged**
